/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "../common/rpc.h"
#include "../common/rpc_api.h"
#include "rpc_clnt.h"

gint main(int argc, char *argv[])
{
    char *host;
    guchar username[MAX_LEN_USERNAME] = "panzehua";
    guchar userip[MAX_LEN_USERIP]     = "172.168.0.1";
    guchar passwd[MAX_LEN_PASSWD]     = "123";

    if (argc < 2)
    {
        printf("usage: %s server_host\n", argv[0]);
        exit(1);
    }
    host = argv[1];

    call_remote(host, userip, username, passwd, 2);
}
